"""V4 DeviceAdapter"""
import abc
class DeviceAdapter(abc.ABC):
    @property
    @abc.abstractmethod
    def name(self): ...
    @abc.abstractmethod
    def connect(self): ...
    @abc.abstractmethod
    def disconnect(self): ...
    @abc.abstractmethod
    def send(self, data): ...
    @abc.abstractmethod
    def on_data(self, cb): ...
