# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: communication.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\nuav_server\"\xa3\x01\n\x0b\x46rameHeader\x12\r\n\x05magic\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x10\n\x08msg_type\x18\x03 \x01(\r\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t\x12\x10\n\x08sequence\x18\x06 \x01(\r\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x16\n\x0epayload_length\x18\x08 \x01(\r\"g\n\tHeartbeat\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\t\"E\n\nAckMessage\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63k_sequence\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"[\n\x12\x43ommunicationFrame\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.uav_server.FrameHeader\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x03 \x01(\r*z\n\x0bMessageType\x12\r\n\tHEARTBEAT\x10\x00\x12\x08\n\x04GNSS\x10\x01\x12\x07\n\x03IMU\x10\x02\x12\n\n\x06STATUS\x10\x03\x12\x11\n\rFILE_TRANSFER\x10\x04\x12\x07\n\x03\x41\x43K\x10\x05\x12\x08\n\x04NACK\x10\x06\x12\n\n\x06\x43ONFIG\x10\x07\x12\x0b\n\x07\x43OMMAND\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=470
  _globals['_MESSAGETYPE']._serialized_end=592
  _globals['_FRAMEHEADER']._serialized_start=36
  _globals['_FRAMEHEADER']._serialized_end=199
  _globals['_HEARTBEAT']._serialized_start=201
  _globals['_HEARTBEAT']._serialized_end=304
  _globals['_ACKMESSAGE']._serialized_start=306
  _globals['_ACKMESSAGE']._serialized_end=375
  _globals['_COMMUNICATIONFRAME']._serialized_start=377
  _globals['_COMMUNICATIONFRAME']._serialized_end=468
# @@protoc_insertion_point(module_scope)
