# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gnss.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'gnss.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngnss.proto\x12\nuav_server\"\xc5\x02\n\x0cGNSSPosition\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08msg_type\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x0e\n\x06height\x18\x05 \x01(\x01\x12\x15\n\rsolution_type\x18\x06 \x01(\x05\x12\x10\n\x08\x64iff_age\x18\x07 \x01(\x01\x12\x12\n\nstation_id\x18\x08 \x01(\t\x12\x16\n\x0esource_channel\x18\t \x01(\t\x12\x10\n\x08raw_data\x18\n \x01(\x0c\x12\x11\n\tgnss_time\x18\x0b \x01(\x03\x12\x12\n\ne_accuracy\x18\x0c \x01(\x01\x12\x12\n\nn_accuracy\x18\r \x01(\x01\x12\x12\n\nu_accuracy\x18\x0e \x01(\x01\x12\x11\n\tserver_id\x18\x0f \x01(\t\x12\x12\n\ncreated_at\x18\x10 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GNSSPOSITION']._serialized_start=27
  _globals['_GNSSPOSITION']._serialized_end=352
# @@protoc_insertion_point(module_scope)
